### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by iceman201** [AndrewBoryk/ABMediaView#1]
how to detect if the video play when it's end?
didnt see any delegate on there

**Comment by AndrewBoryk** [comment]
Currently, there are delegate methods for pause and play. Delegate for when the video ends/loops would be good to have. I've been wanting to put an update to this project. Currently I was working on converting this to Swift. 

What else would be desirable in the delegate (for the Objective-C project)?

**Comment by iceman201** [comment]
```
    func mediaViewWillPresent(_ mediaView: ABMediaView!) {
        NotificationCenter.default.addObserver(self, selector: #selector(self.didPlayToEnd), name: .AVPlayerItemDidPlayToEndTime, object: nil)
    }
    
    func didPlayToEnd() {
        print("hahaha")
    }
```

Actually, I just figure out how to make it work. Since your ABPlayer is AVplayer, so it could just create an observe listener the AVplayer status. lol

I think your delegate has already cover quite large range usages.
Awesome framework man

**Comment by iceman201** [comment]
would be nice if it has something like "dismiss full screen after play til end of the video"?

**Comment by AndrewBoryk** [comment]
I committed an updated to dev
`- (void)mediaViewDidFinishVideo:(ABMediaView *)mediaView withLoop:(BOOL)didLoop;`

And thanks for the compliment! This started as just a project to play around with the minimization idea, and I figured I could keep building on it. Still a lot that I want to do, I just got settled into a new job, so I plan on getting back to adding features to this. 

To clarify on the feature you just proposed, you mean something like "dismissAfterVideoCompletion" and then after a video completes playing, the view will automatically close?

**Comment by iceman201** [comment]
yes like that, Congratulation for your new job btw lol

**Comment by iceman201** [comment]
is there anyway could dismiss that fullscreen manually???

**Comment by AndrewBoryk** [comment]
Yes^ By calling
```
[mediaView dismissMediaViewAnimated:YES withCompletion:^(BOOL completed) {
    // Executes after mediaView finishes dismissing itself
}];
```

Please refer to the "Calling the Manager" section of the Documentation

**Comment by iceman201** [comment]
hm.....
if i just do mediaView.sharedManager() it will return me error.

if i do ABMediaView.sharedManager() it gives me this 
![image](https://user-images.githubusercontent.com/5027957/27638663-1bb53e02-5c68-11e7-8554-0176fb9bb192.png)

**Comment by AndrewBoryk** [comment]
The function I just sent you is called on the mediaView itself, not on the shared manager. I've been thinking about moving that function in the docs, and adding a section for Presentation and Dismissal

**Comment by iceman201** [comment]
even i use this `postVideo.dismiss(animated: true, withCompletion: nil)` still doesnt dismiss when its playing in fullscreen.

**Comment by AndrewBoryk** [comment]
Hmm I will look at this tomorrow, and I'll get a new version out to you with a few updates. Is that cool?

**Comment by iceman201** [comment]
Cool awesome.

Thanks in advance



On 29/06/2017, at 1:08 PM, Andrew Boryk <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm I will look at this tomorrow, and I'll get a new version out to you with a few updates. Is that cool?
